"""add isdisable

Revision ID: fa71d8d12a34
Revises: 22991c80ed08
Create Date: 2018-07-31 00:23:45.651119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa71d8d12a34'
down_revision = '22991c80ed08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_disable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_disable')
    # ### end Alembic commands ###
